server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookitem?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 1339218991fks
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
